workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
    - validate
    - plan
    - scan

variables:
  ROOT_DIR: ./envs/dev
  TFPLAN_FILE: "tfplan"
  GITLAB_TOKEN: $GITLAB_TOKEN

before_script:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - rm -rf .terraform
  - terraform version
  - terragrunt version
  - terragrunt run-all init

validate:
  stage: validate
  script: |
    terragrunt hclfmt
    terragrunt run-all validate
    terraform fmt --recursive

plan:
  stage: plan
  dependencies:
    - validate
  script: 
    - terragrunt run-all plan -out=$TFPLAN_FILE
    - terraform show -no-color plan > $TFPLAN_FILE
    - |
      curl --request POST --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
                          --data "body=$(cat $TFPLAN_FILE)" \
                          $CI_SERVER_URL/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/discussions

  artifacts:
    paths:
      - $ROOT_DIR/$TFPLAN_FILE

checkov:
  stage: scan
  allow_failure: true
  script:
    - echo "Scanning checkov ..."
    - checkov -f $TFPLAN_FILE

infracost:
  stage: scan
  variables:
    INFRACOST_API_KEY: $INFRACOST_API_KEY
  script: 
    - echo "Scanning infracost ..."
    - infracost configure set api_key $INFRACOST_API_KEY
    - |
      infracost breakdown --path $ROOT_DIR \
                          --format json \
                          --out-file infracost-base.json

    - |
      infracost diff --path $ROOT_DIR \
                    --compare-to infracost-base.json \
                    --format json \
                    --out-file infracost.json
    - |
      infracost comment gitlab --path infracost.json \
                          --repo $CI_PROJECT_PATH \
                          --merge-request $CI_MERGE_REQUEST_IID \
                          --gitlab-server-url $CI_SERVER_URL \
                          --gitlab-token $GITLAB_TOKEN \
                          --behavior=delete-and-new


# tflint:
#   stage: scan
#   script: |
#     tflint

# tfsec:
#   stage: scan
#   script: |
#     tfsec
