# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
    - .pre
    - init
    - validate
    - scan
    - plan
    - .post

init:
  stage: init
  script: |
    terraform -version
    terraform init

validate:
  stage: validate
  script: |
    terraform fmt -check
    terraform validate

checkov:
  stage: scan
  script: |
    checkov -d .

infracost:
  stage: scan
  script: |
    infracost diff --path . --compare-to infracost-base.json
    infracost breakdown --path . --format json --out-file infracost-base.json
    # infracost upload --path infracost-base.json

tflint:
  stage: scan
  script: |
    echo "tflint"

tfsec:
  stage: scan
  script: |
    echo "tfsec"

terraform-plan:
  stage: plan
  script: |
    terraform plan
