# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
    - .pre
    - validate
    - init
    - scan
    - plan
    - .post


validate:
  stage: validate
  script: |
    terragrunt hclfmt
    terraform fmt --recursive

init:
  stage: init
  script: |
    cd /envs/dev # Replace to corresponding envs
    terraform version
    terragrunt version
    terragrunt run-all init

checkov:
  stage: scan
  script: |
    checkov -d .

infracost:
  stage: scan
  script: |
    infracost breakdown --path . 

tflint:
  stage: scan
  script: |
    tflint

tfsec:
  stage: scan
  script: |
    tfsec

terraform-plan:
  stage: plan
  script: |
    terragrunt run-all plan
