---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@mydomain.com
    privateKeySecretRef:
      name: letsencrypt-staging-http01-key-pair
    solvers:
    - http01: # cert-manager will create a temporary ingress using the ingress class below to prove to let's encrypt that we own the domain and server
        ingress:
          class: nginx # this ingress class will be used to solve the challenge
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@mydomain.com
    privateKeySecretRef:
      name: letsencrypt-prod-http01-key-pair
    solvers:
    - http01:
        ingress:
          class: nginx
