kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-admin
  namespace: devteam-a
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: sso:DevTeam-A@your_domain
    apiGroup: rbac.authorization.k8s.io