stages:
    - .pre
    - init
    - validate
    - scan
    - plan
    - .post

init:
  stage: init
  script: |
    terraform -version
    terraform init

validate:
  stage: validate
  script: |
    terraform fmt --recursive
    terraform validate

checkov:
  stage: scan
  script: |
    echo "Scanning checkov ..."
    checkov -d .

infracost:
  stage: scan
  variables:
    INFRACOST_API_KEY: xxxxxx
  script: |
    echo "Scanning infracost ..."
    # infracost diff --path . --compare-to infracost-base.json
    # infracost breakdown --path . --format json --out-file infracost-base.json
    # infracost upload --path infracost-base.json

tflint:
  stage: scan
  script: |
    echo "Scanning tflint ..."
    tflint

tfsec:
  stage: scan
  script: |
    echo "Scanning tfsec ..."
    tfsec

terraform-plan:
  stage: plan
  script: |
    terraform plan
