stages:
    - .pre
    - init
    - validate
    - scan
    - plan
    - .post

init:
  stage: init
  script: |
    terraform init

validate:
  stage: validate
  script: |
    terraform validate

checkov:
  stage: scan
  script: |
    echo "checkov"

infracost:
  stage: scan
  script: |
    echo "infracost"

tflint:
  stage: scan
  script: |
    echo "tflint"

tfsec:
  stage: scan
  script: |
    echo "tfsec"

terraform-plan:
  stage: plan
  script: |
    terraform plan
