apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -dev

resources: # each envs has its own configmap
  - configmap.yaml

patchesStrategicMerge:
  - ingress.yaml
