# Example of how a Pod can leverage IRSA to retrieve AWS STS token by calling AssumeRoleWithWebIdentity API with SA annotations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: irsa-freddieentity-application
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::158904540988:role/irsa-freddieentity-application
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: irsa-freddieentity-application
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  tolerations:
  - operator: Exists
    effect: NoSchedule