# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
---
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.127.0.0.1.nip.io
      # - &host argocd.127.0.0.1.nip.io
    paths:
      - /
    # tls:
    #   - secretName: argocd-tls-certificate
    #     hosts:
    #       - *host
  metrics: &metrics
    enabled: true
    serviceMonitor:
      enabled: true
dex:
  enabled: true
controller:
  metrics: *metrics
repoServer:
  metrics: *metrics
redis:
  metrics: *metrics