---
installCRDs: true
# prometheus:
#   enabled: true
#   servicemonitor:
#     enabled: true
#     prometheusInstance: spoke1
# DNS-01 Route53
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::158904540988:role/irsa-freddieentity-cert-manager
extraArgs: 
- --issuer-ambient-credentials
