---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@freddieentity.link
    privateKeySecretRef:
      name: letsencrypt-staging-dns01-key-pair
    solvers:
    - dns01: # Must have an IRSA in the cert-manager deployment to interact with AWS Route53.
        route53:
          region: us-east-1
          hostedZoneID: Z09621583CLDS49SID728 # freddieentity.link hosted zone id
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@freddieentity.link
    privateKeySecretRef:
      name: letsencrypt-prod-dns01-key-pair
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z09621583CLDS49SID728