apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: freddieentity.link
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend
            port:
              number: 80